import React, {useState, useEffect} from "react"
import { isAuthenticated } from "../auth/helper";
import { cartEmpty, loadCart } from "./helper/cartHelper";
import { Link } from "react-router-dom";
import StripeCheckoutButton from "react-stripe-checkout"
import {API} from "../backend"
import createOrder from "../core/helper/orderHelper"
//4242 4242 4242 4242

const StripeCheckout = ({
    products,
    setReload = f => f,
    reload = undefined
}) => {

    const [data, setData] = useState({
        loading: false,
        success: false,
        error: "",
        address: ""
    })

    const token = isAuthenticated() && isAuthenticated().token
    const userId = isAuthenticated() && isAuthenticated().user._id

    const getFinalAmount =() => {
        let amount = 0;
        products.map(p => {
            amount = amount + p.price
        })
        return amount;
    }

    const makePayment = token => {
        const body = {
            token,//this token is automatically generated by stripe and it is different from the authentication token
            products//we are passing products in backend to calculate the amount
        }
        const headers = {
            "Content-Type": "application/json"
        }
        return fetch(`${API}/stripepayment`, {
            method: "POST",
            headers,
            body: JSON.stringify(body)
        }).then(response => {
            console.log(response)
            const {status} = response
            console.log("STATUS", status)
            cartEmpty(() => {
                console.log("cart emptied after doing payment with stripe")
            })
            setReload(!reload)
        }).catch(err => console.log(err))
    }

    const showStripeButton = () => {   //user can only checkout if he is logged in
        return isAuthenticated() ? (
            <StripeCheckoutButton
            stripeKey="pk_test_rkQ2FvHYF91bb0ZoP9BtxaUH002XB3Iu8S" //this is the publishable key it should be in the env file
            token={makePayment}
            amount={getFinalAmount() * 100 }
            name="Buy Tshirt"
            shippingAddress
            billingAddress
            >
                <button className="btn btn-block btn-success">Pay with stripe</button>
            </StripeCheckoutButton>
        ) : (
            <Link to = "/signin">
                <button  className="btn btn-warning">Signin</button>
            </Link>
        )
    }

    

    return(
        <div id="stripe">
            <h3 className="text-white">Stripe Checkout {getFinalAmount()}$</h3>
            {showStripeButton()}
        </div>
    )
}

export default StripeCheckout;